apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: backend
          image: sist1.azurecr.io/server:latest
          ports:
            - containerPort: 5001
        - name: frontend
          image: sist1.azurecr.io/frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
    - name: backend
      port: 5001
      targetPort: 5001
    - name: frontend
      port: 3000
      targetPort: 3000
  type: LoadBalancer